# Eureka client
spring:
  application:
    name: webclient
server:
  port: 8762
eureka:
  client:
    serviceUrl:
     defaultZone: http://eurekapeer1:8761/eureka/
  instance:
    prefer-ip-address: true # 设置为ip 模式
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds : 10   # 续约到期时间（默认90秒）

feign:
  hystrix:
    enable : true #开启hystrix,默认是false,这个是必须的开放，否则会出现找不到消费者或者拒绝连接的错误
  compression:
    request:
      mime-types: text/xml;application/xml;application/json #指定压缩请求数据类型
      min-request-size : 2048 #如果传输超过该字节，就对其进行压缩

##ribbo负载均衡策略配置，默认是依次轮询
API-USER-SERVER.ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
#Hystrix断路器的超时时间，默认是1s
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000